### ISSUE TITLE
Implement Frame Switch

### ISSUE THREAD

**Issue by ty-desj** [StatCan/tass-ssat#32]

**Comment by DominicParent** [comment]
@ty-desj I approved the merge request. I noticed when running flake8 that there were two lines with some issues:
.\tass\actions\actions.py:4:1: W293 blank line contains whitespace
.\tass\actions\actions.py:12:56: W292 no newline at end of file
but those made it through a different merge. We just need to clean it up in one of our future modifications to the code.

Also, please make sure to add some unittest for the new frame switching. In this context of doing quick automation during a test, we can skip it pretty safely (we're pre 1.0.0, after all). I'll be creating a git issue for this #36 so that we remember to do it later.
